kind: List
apiVersion: v1beta1
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: cfssl
  spec:
    replicas: 1
    template:
      metadata:
        name: cfssl
        labels:
          app: cfssl
          tier: cfssl
      spec:
        volumes:
        - emptyDir: {}
          name: dir-1
        containers:
        - image: blackducksoftware/hub-cfssl:4.4.2
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/docker-healthcheck.sh
              - http://localhost:8888/api/v1/cfssl/scaninfo
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          imagePullPolicy: Always
          resources:
            requests:
              memory: 640M
            limits:
              memory: 640M
          name: hub-cfssl
          envFrom:
          - configMapRef:
              name: "hub-config"
          volumeMounts:
          - mountPath: /etc/cfssl
            name: dir-1
          ports:
          - containerPort: 8888
          env:
           - name: HUB_VERSION
             value: 4.4.2
- apiVersion: v1
  kind: Service
  metadata:
    name: cfssl
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      targetPort: 8888
    selector:
      app: cfssl
  status:
    loadBalancer: {}
