kind: List
apiVersion: v1beta1
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: postgres
  spec:
    replicas: 1
    template:
      metadata:
        name: postgres
        labels:
          app: postgres
          tier: postgres
      spec:
        volumes:
        - name: postgres-persistent-vol
          hostPath:
            path: /var/lib/hub-postgresql/data
        containers:
        - name: postgres
          image: blackducksoftware/hub-postgres:4.4.2
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/docker-healthcheck.sh
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          imagePullPolicy: Always
          resources:
            requests:
              memory: 6144M
              cpu: 2
          envFrom:
          - configMapRef:
              name: hub-config
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-persistent-vol
          ports:
          - containerPort: 5432
          env:
          - name: HUB_VERSION
            value: 4.4.2
        nodeSelector:
           blackduck.hub.postgres: "true"
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      targetPort: 5432
    selector:
      app: postgres
  status:
    loadBalancer: {}
