kind: List
apiVersion: v1beta1
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: solr
  spec:
    replicas: 1
    template:
      metadata:
        name: solr
        labels:
          app: solr
          tier: solr
      spec:
        containers:
        - name: solr
          resources:
            requests:
              memory: "640M"
            limits:
              memory: "640M"
          image: blackducksoftware/hub-solr:4.4.2
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - http://localhost:8983/solr/project/admin/ping?wt=json
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          env:
          - name: HUB_VERSION
            value: 4.4.2
- apiVersion: v1
  kind: Service
  metadata:
    name: solr
  spec:
    ports:
    - name: 8983-tcp
      port: 8983
      targetPort: 8983
    selector:
      app: solr
