kind: List
apiVersion: v1beta1
items:
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: zookeeper
  spec:
    replicas: 1
    template:
      metadata:
        name: zookeeper
        labels:
          app: zookeeper
          tier: zookeeper
      spec:
        volumes:
        - emptyDir: {}
          name: dir-1
        containers:
        - envFrom:
          - configMapRef:
              name: hub-config
          image: blackducksoftware/hub-zookeeper:4.4.2
          livenessProbe:
            exec:
              command:
                - zkServer.sh
                - status
                - /opt/blackduck/zookeeper/conf/zoo.cfg
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
          imagePullPolicy: Always
          name: zookeeper
          resources:
            requests:
              memory: 384M
            limits:
              memory: 384M
          volumeMounts:
            - mountPath: "/opt/blackduck/hub/logs"
              name: dir-1
          env:
          - name: HUB_VERSION
            value: 4.4.2
- apiVersion: v1
  kind: Service
  metadata:
    name: zookeeper
  spec:
    ports:
    - name: 2181-tcp
      port: 2181
      targetPort: 2181
    selector:
      app: zookeeper
  status:
    loadBalancer: {}
